#!/bin/zsh

here=${0:a:h}

ln -sv $here/gitconfig ~/.gitconfig
ln -sv $here/gitignore ~/.gitignore
ln -sv $here/direnvrc ~/.direnvrc
ln -sv $here/.editorconfig ~/.editorconfig

if command -v hidutil &> /dev/null; then
	mkdir -p ~/Library/LaunchAgents
	ln -sv $here/KeyRemapping.plist ~/Library/LaunchAgents/KeyRemapping.plist
	launchctl load ~/Library/LaunchAgents/KeyRemapping.plist
fi

mkdir -p ~/.config
ln -sv $here/kitty ~/.config/kitty
ln -sv $here/nvim-lua ~/.config/nvim

ln -sv $here/zprofile ~/.zprofile
ln -sv $here/zshrc ~/.zshrc
ln -sv $here/zsh-plugins ~/.zsh-plugins
ln -sv $here/p10k.zsh ~/.p10k.zsh
